fastadir : "/well/shaw/users/amu125/data/CARD/betalactamases/fasta/"
region_upstream : "5000"
region_downstream : "5000"
pangraph_polish : True
pangraph_aligner : "minimap2"
pangraph_minblocklength : "100"

