# directory with fasta files containing genes of interest
fastadir : "/Users/Liam/Downloads/betalactamase-contigs"
region_upstream : "1000"
region_downstream : "1000"
pangraph_polish : False
pangraph_aligner : "minimap2"
pangraph_minblocklength : "500"
